---
title: "workshop-09"
format: html
editor: visual
---

```{r}
# Load libraries
library(tidyverse)
library(lterdatasampler)
library(ggeffects)
library(here)
```

```{r}
# Load data
data(pie_crab)
view(pie_crab)

```

exploratory vis

```{r}
ggplot(aes(x = latitude, y = size), data = pie_crab) + # set up plot
geom_point(color = "pink") + # make pink scatterplot
  labs(x = "latitude", y = "size (mm)") + #labels
  theme_minimal() # remove gridlines

```

writing a model

```{r}
crab_model <- lm(size ~ latitude, # formula: response ~ predictor
                 data = pie_crab) # data from lter data sampler

# look at diagnostics
par(mfrow = c(2,2)) # plot diagnostics 2x2 grid
plot(crab_model) #plotting diagnostics
```

interpret model

```{r}
summary(crab_model) # look at results
```

Slope: 0.49 +/- 0.034 
Y-intercept: -3.62 +/- 1.27
For every one increase in latitude, we expect to see an increase in crab size of 0.49 +/- 0.034 mm. 

Model statistics: F(1,390) = 208.5, p < 0.001 , alpha = 0.05, R^2 = 0.34

